### ISSUE TITLE
unable to generate *.scr for eagle cad

### ISSUE THREAD

**Issue by ekawahyu** [rbuj/FreeRouting#6]
I managed to generate the *dsn file, open it with FreeRouting, but it was not able to generate *.scr for eagle. Is this a known issue? I tried to generate *.dsn with eagle2freerouter.ulp and eagle2freerouterV6-5.ulp. I tried to use Eagle v6 and Eagle v7 with no luck. I have JDK and JRE v9 installed and tried to build FreeRouting v1.4.5-alpha, v1.4.4, and v1.4.2 without any problem, but all of them failed to save *.scr. What do you think I might do wrong? My system is OS X 10.10.5.

**Comment by rbuj** [comment]
"Export Eagle Session Script" is disabled by default, as it's an experimental feature. To enable it, you can append "-test" argument at the command line.

**Comment by ekawahyu** [comment]
which command line? the maven build or when executing the jar? could you elaborate a little bit about it please?

I don't know if I did it right, but `mvn -test install` and `java -jar freerouting-[version].jar -test` are both failed to generate *.scr

**Comment by rbuj** [comment]
"Export Eagle Session Script" has not been developed for a while, in fact we can remove it because we can consider that it's deprecated now, as there are other open software E-CADs which support SPECCTRA session file format like [KiCAD](http://kicad-pcb.org/). There is more info available at [KiCAD manual: Automatically route with FreeRouter
](http://docs.kicad-pcb.org/stable/en/getting_started_in_kicad.html#automatically-route-with-freerouter)

**Comment by ekawahyu** [comment]
Well, since the menu is still there, I was expecting it to work for Eagle CAD. If there is no way to enable it or to make it functional, then I would suggest to remove "export eagle session script" from the menu. You may close this issue since I won't get the answer I need. Thank you.
